"""
Allowlists for Dippy - known safe commands and transparent wrappers.
"""

# === Simple Safe Commands ===
# These are always safe regardless of arguments (except output redirects)

SIMPLE_SAFE = frozenset(
    {
        # === File Content Viewing ===
        "cat",
        "head",
        "tail",
        "less",
        "more",
        "bat",
        "tac",
        "od",
        "hexdump",
        "strings",
        # Compressed file viewers
        "bzcat",
        "bzmore",
        "funzip",
        "lz4cat",
        "xzcat",
        "xzless",
        "xzmore",
        "zcat",
        "zless",
        "zmore",
        "zstdcat",
        "zstdless",
        # Archive inspection
        "zipinfo",
        # === Binary Analysis ===
        "dwarfdump",
        "dyld_info",
        "ldd",
        "nm",
        "objdump",
        "otool",
        "readelf",
        "size",
        # === Directory Listing ===
        "ls",
        "ll",
        "la",
        "tree",
        "exa",
        "eza",
        "dir",
        "vdir",
        # === File & Disk Information ===
        "stat",
        "file",
        "wc",
        "du",
        "df",
        # === Path Utilities ===
        "basename",
        "dirname",
        "pwd",
        "cd",
        "readlink",
        "realpath",
        # === Search & Find ===
        "grep",
        "rg",
        "ripgrep",
        "ag",
        "ack",
        "fd",
        "fzf",
        "locate",
        "look",
        "mdfind",
        "mdls",
        # === Text Processing ===
        "uniq",
        "cut",
        "col",
        "colrm",
        "column",
        "comm",
        "cmp",
        "diff",
        "diff3",
        "diffstat",
        "expand",
        "fmt",
        "fold",
        "jot",
        "join",
        "lam",
        "nl",
        "paste",
        "pr",
        "rev",
        "rs",
        "seq",
        "tr",
        "tsort",
        "ul",
        "unexpand",
        "unvis",
        "vis",
        "what",
        # Calculators
        "bc",
        "dc",
        "expr",
        "units",
        # === Structured Data (JSON/YAML/XML) ===
        "jq",
        "yq",
        "xq",
        # === Encoding & Checksums ===
        "base64",
        "md5sum",
        "sha1sum",
        "sha256sum",
        "sha512sum",
        "b2sum",
        "cksum",
        "md5",
        "shasum",
        "sum",
        # === User & System Information ===
        "whoami",
        "hostname",
        "hostinfo",
        "uname",
        "sw_vers",
        "id",
        "finger",
        "groups",
        "last",
        "locale",
        "logname",
        "users",
        "w",
        "who",
        "klist",
        # Date & time
        "date",
        "cal",
        "uptime",
        # System configuration
        "getconf",
        "machine",
        "pagesize",
        # === Process & Resource Monitoring ===
        "atos",
        "btop",
        "dmesg",
        "footprint",
        "free",
        "fs_usage",
        "fuser",
        "heap",
        "htop",
        "ioreg",
        "iostat",
        "ipcs",
        "leaks",
        "lskq",
        "lsmp",
        "lsof",
        "lsvfs",
        "lpstat",
        "nettop",
        "pgrep",
        "powermetrics",
        "ps",
        "sample",
        "system_profiler",
        "top",
        "vm_stat",
        "vmmap",
        "vmstat",
        # === Environment & Output ===
        "printenv",
        "echo",
        "printf",
        # === Network Diagnostics ===
        "ping",
        "host",
        "dig",
        "nslookup",
        "traceroute",
        "mtr",
        "netstat",
        "ss",
        "arp",
        "route",
        "whois",
        # === Command Lookup & Help ===
        "which",
        "whereis",
        "type",
        "command",
        "hash",
        "man",
        "help",
        "info",
        "tldr",
        # === Code Quality & Linting ===
        "cloc",
        "mypy",
        "black",
        "isort",
        "flake8",
        "pre-commit",
        # === Media & Image Info ===
        "afinfo",
        "ffprobe",
        "heif-info",
        "identify",
        "opj_dump",
        "rdjpgcom",
        "sndfile-info",
        "tiffdump",
        "tiffinfo",
        "webpinfo",
        # === Shell Builtins & Utilities ===
        "true",
        "false",
        "sleep",
        "read",
        # === Terminal ===
        "clear",
        "reset",
        "tput",
        "tty",
    }
)


# === Transparent Wrappers ===
# Commands that wrap other commands - we analyze the inner command instead

WRAPPER_COMMANDS = frozenset(
    {
        "time",
        "timeout",
        "nice",
        "nohup",
        "strace",
        "ltrace",
        "command",
        "builtin",
    }
)
